# Generated by Makefile. Do not edit.
CC = icl
CXX = $(CC)

CFLAGS = /nologo /Wall /wd4464 /wd4514
CXXFLAGS = $(CFLAGS)

TESTS = \
	array-param.exe array-param-cpp.exe \
	assume.exe assume-cpp.exe \
	cast.exe cast-cpp.exe \
	concat.exe concat-cpp.exe \
	const.exe const-cpp.exe \
	constant.exe constant-cpp.exe \
	deprecated.exe deprecated-cpp.exe \
	empty-bases.exe empty-bases-cpp.exe \
	fallthrough.exe fallthrough-cpp.exe \
	flags.exe flags-cpp.exe \
	inline.exe inline-cpp.exe \
	likely.exe likely-cpp.exe \
	malloc.exe malloc-cpp.exe \
	message.exe message-cpp.exe \
	noinline.exe noinline-cpp.exe \
	no-escape.exe no-escape-cpp.exe \
	no-return.exe no-return-cpp.exe \
	non-null.exe non-null-cpp.exe \
	predict.exe predict-cpp.exe \
	printf-format.exe printf-format-cpp.exe \
	pure.exe pure-cpp.exe \
	require.exe require-cpp.exe \
	restrict.exe restrict-cpp.exe \
	returns-non-null.exe returns-non-null-cpp.exe \
	sentinel.exe sentinel-cpp.exe \
	static-assert.exe static-assert-cpp.exe \
	stringify.exe stringify-cpp.exe \
	unknown-cpp-attributes.exe unknown-cpp-attributes-cpp.exe \
	unknown-pragmas.exe unknown-pragmas-cpp.exe \
	unavailable.exe unavailable-cpp.exe \
	unreachable.exe unreachable-cpp.exe \
	visibility.exe visibility-cpp.exe \
	warn.exe warn-cpp.exe \
	warn-unused-result.exe warn-unused-result-cpp.exe \
	$(NULL)

TESTS = \
	array-param.exe array-param-cpp.exe \
	assume.exe assume-cpp.exe \
	cast.exe cast-cpp.exe \
	concat.exe concat-cpp.exe \
	const.exe const-cpp.exe \
	constant.exe constant-cpp.exe \
	deprecated.exe deprecated-cpp.exe \
	empty-bases.exe empty-bases-cpp.exe \
	fallthrough.exe fallthrough-cpp.exe \
	flags.exe flags-cpp.exe \
	inline.exe inline-cpp.exe \
	likely.exe likely-cpp.exe \
	malloc.exe malloc-cpp.exe \
	message.exe message-cpp.exe \
	noinline.exe noinline-cpp.exe \
	no-escape.exe no-escape-cpp.exe \
	no-return.exe no-return-cpp.exe \
	non-null.exe non-null-cpp.exe \
	predict.exe predict-cpp.exe \
	printf-format.exe printf-format-cpp.exe \
	pure.exe pure-cpp.exe \
	require.exe require-cpp.exe \
	restrict.exe restrict-cpp.exe \
	returns-non-null.exe returns-non-null-cpp.exe \
	sentinel.exe sentinel-cpp.exe \
	static-assert.exe static-assert-cpp.exe \
	stringify.exe stringify-cpp.exe \
	unknown-cpp-attributes.exe unknown-cpp-attributes-cpp.exe \
	unknown-pragmas.exe unknown-pragmas-cpp.exe \
	unavailable.exe unavailable-cpp.exe \
	unreachable.exe unreachable-cpp.exe \
	visibility.exe visibility-cpp.exe \
	warn.exe warn-cpp.exe \
	warn-unused-result.exe warn-unused-result-cpp.exe \
	$(NULL)

CLEANFILES = $(TESTS) \
	array-param.cpp array-param.obj array-param.lib array-param-cpp.exp array-param-cpp.lib \
	assume.cpp assume.obj assume.lib assume-cpp.exp assume-cpp.lib \
	cast.cpp cast.obj cast.lib cast-cpp.exp cast-cpp.lib \
	concat.cpp concat.obj concat.lib concat-cpp.exp concat-cpp.lib \
	const.cpp const.obj const.lib const-cpp.exp const-cpp.lib \
	constant.cpp constant.obj constant.lib constant-cpp.exp constant-cpp.lib \
	deprecated.cpp deprecated.obj deprecated.lib deprecated-cpp.exp deprecated-cpp.lib \
	empty-bases.cpp empty-bases.obj empty-bases.lib empty-bases-cpp.exp empty-bases-cpp.lib \
	fallthrough.cpp fallthrough.obj fallthrough.lib fallthrough-cpp.exp fallthrough-cpp.lib \
	flags.cpp flags.obj flags.lib flags-cpp.exp flags-cpp.lib \
	inline.cpp inline.obj inline.lib inline-cpp.exp inline-cpp.lib \
	likely.cpp likely.obj likely.lib likely-cpp.exp likely-cpp.lib \
	malloc.cpp malloc.obj malloc.lib malloc-cpp.exp malloc-cpp.lib \
	message.cpp message.obj message.lib message-cpp.exp message-cpp.lib \
	noinline.cpp noinline.obj noinline.lib noinline-cpp.exp noinline-cpp.lib \
	no-escape.cpp no-escape.obj no-escape.lib no-escape-cpp.exp no-escape-cpp.lib \
	no-return.cpp no-return.obj no-return.lib no-return-cpp.exp no-return-cpp.lib \
	non-null.cpp non-null.obj non-null.lib non-null-cpp.exp non-null-cpp.lib \
	predict.cpp predict.obj predict.lib predict-cpp.exp predict-cpp.lib \
	printf-format.cpp printf-format.obj printf-format.lib printf-format-cpp.exp printf-format-cpp.lib \
	pure.cpp pure.obj pure.lib pure-cpp.exp pure-cpp.lib \
	require.cpp require.obj require.lib require-cpp.exp require-cpp.lib \
	restrict.cpp restrict.obj restrict.lib restrict-cpp.exp restrict-cpp.lib \
	returns-non-null.cpp returns-non-null.obj returns-non-null.lib returns-non-null-cpp.exp returns-non-null-cpp.lib \
	sentinel.cpp sentinel.obj sentinel.lib sentinel-cpp.exp sentinel-cpp.lib \
	static-assert.cpp static-assert.obj static-assert.lib static-assert-cpp.exp static-assert-cpp.lib \
	stringify.cpp stringify.obj stringify.lib stringify-cpp.exp stringify-cpp.lib \
	unknown-cpp-attributes.cpp unknown-cpp-attributes.obj unknown-cpp-attributes.lib unknown-cpp-attributes-cpp.exp unknown-cpp-attributes-cpp.lib \
	unknown-pragmas.cpp unknown-pragmas.obj unknown-pragmas.lib unknown-pragmas-cpp.exp unknown-pragmas-cpp.lib \
	unavailable.cpp unavailable.obj unavailable.lib unavailable-cpp.exp unavailable-cpp.lib \
	unreachable.cpp unreachable.obj unreachable.lib unreachable-cpp.exp unreachable-cpp.lib \
	visibility.cpp visibility.obj visibility.lib visibility-cpp.exp visibility-cpp.lib \
	warn.cpp warn.obj warn.lib warn-cpp.exp warn-cpp.lib \
	warn-unused-result.cpp warn-unused-result.obj warn-unused-result.lib warn-unused-result-cpp.exp warn-unused-result-cpp.lib \
	$(NULL)

all: $(TESTS)

clean:
	del /Q $(CLEANFILES)

array-param.exe: array-param.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
array-param.cpp: array-param.c
	copy /Y $(?) $(@) >NUL
array-param-cpp.exe: array-param.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

assume.exe: assume.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
assume.cpp: assume.c
	copy /Y $(?) $(@) >NUL
assume-cpp.exe: assume.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

cast.exe: cast.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
cast.cpp: cast.c
	copy /Y $(?) $(@) >NUL
cast-cpp.exe: cast.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

concat.exe: concat.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
concat.cpp: concat.c
	copy /Y $(?) $(@) >NUL
concat-cpp.exe: concat.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

const.exe: const.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
const.cpp: const.c
	copy /Y $(?) $(@) >NUL
const-cpp.exe: const.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

constant.exe: constant.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
constant.cpp: constant.c
	copy /Y $(?) $(@) >NUL
constant-cpp.exe: constant.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

deprecated.exe: deprecated.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
deprecated.cpp: deprecated.c
	copy /Y $(?) $(@) >NUL
deprecated-cpp.exe: deprecated.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

empty-bases.exe: empty-bases.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
empty-bases.cpp: empty-bases.c
	copy /Y $(?) $(@) >NUL
empty-bases-cpp.exe: empty-bases.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

fallthrough.exe: fallthrough.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
fallthrough.cpp: fallthrough.c
	copy /Y $(?) $(@) >NUL
fallthrough-cpp.exe: fallthrough.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

flags.exe: flags.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
flags.cpp: flags.c
	copy /Y $(?) $(@) >NUL
flags-cpp.exe: flags.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

inline.exe: inline.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
inline.cpp: inline.c
	copy /Y $(?) $(@) >NUL
inline-cpp.exe: inline.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

likely.exe: likely.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
likely.cpp: likely.c
	copy /Y $(?) $(@) >NUL
likely-cpp.exe: likely.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

malloc.exe: malloc.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
malloc.cpp: malloc.c
	copy /Y $(?) $(@) >NUL
malloc-cpp.exe: malloc.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

message.exe: message.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
message.cpp: message.c
	copy /Y $(?) $(@) >NUL
message-cpp.exe: message.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

noinline.exe: noinline.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
noinline.cpp: noinline.c
	copy /Y $(?) $(@) >NUL
noinline-cpp.exe: noinline.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

no-escape.exe: no-escape.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
no-escape.cpp: no-escape.c
	copy /Y $(?) $(@) >NUL
no-escape-cpp.exe: no-escape.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

no-return.exe: no-return.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
no-return.cpp: no-return.c
	copy /Y $(?) $(@) >NUL
no-return-cpp.exe: no-return.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

non-null.exe: non-null.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
non-null.cpp: non-null.c
	copy /Y $(?) $(@) >NUL
non-null-cpp.exe: non-null.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

predict.exe: predict.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
predict.cpp: predict.c
	copy /Y $(?) $(@) >NUL
predict-cpp.exe: predict.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

printf-format.exe: printf-format.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
printf-format.cpp: printf-format.c
	copy /Y $(?) $(@) >NUL
printf-format-cpp.exe: printf-format.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

pure.exe: pure.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
pure.cpp: pure.c
	copy /Y $(?) $(@) >NUL
pure-cpp.exe: pure.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

require.exe: require.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
require.cpp: require.c
	copy /Y $(?) $(@) >NUL
require-cpp.exe: require.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

restrict.exe: restrict.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
restrict.cpp: restrict.c
	copy /Y $(?) $(@) >NUL
restrict-cpp.exe: restrict.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

returns-non-null.exe: returns-non-null.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
returns-non-null.cpp: returns-non-null.c
	copy /Y $(?) $(@) >NUL
returns-non-null-cpp.exe: returns-non-null.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

sentinel.exe: sentinel.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
sentinel.cpp: sentinel.c
	copy /Y $(?) $(@) >NUL
sentinel-cpp.exe: sentinel.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

static-assert.exe: static-assert.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
static-assert.cpp: static-assert.c
	copy /Y $(?) $(@) >NUL
static-assert-cpp.exe: static-assert.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

stringify.exe: stringify.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
stringify.cpp: stringify.c
	copy /Y $(?) $(@) >NUL
stringify-cpp.exe: stringify.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

unknown-cpp-attributes.exe: unknown-cpp-attributes.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
unknown-cpp-attributes.cpp: unknown-cpp-attributes.c
	copy /Y $(?) $(@) >NUL
unknown-cpp-attributes-cpp.exe: unknown-cpp-attributes.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

unknown-pragmas.exe: unknown-pragmas.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
unknown-pragmas.cpp: unknown-pragmas.c
	copy /Y $(?) $(@) >NUL
unknown-pragmas-cpp.exe: unknown-pragmas.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

unavailable.exe: unavailable.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
unavailable.cpp: unavailable.c
	copy /Y $(?) $(@) >NUL
unavailable-cpp.exe: unavailable.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

unreachable.exe: unreachable.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
unreachable.cpp: unreachable.c
	copy /Y $(?) $(@) >NUL
unreachable-cpp.exe: unreachable.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

visibility.exe: visibility.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
visibility.cpp: visibility.c
	copy /Y $(?) $(@) >NUL
visibility-cpp.exe: visibility.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

warn.exe: warn.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
warn.cpp: warn.c
	copy /Y $(?) $(@) >NUL
warn-cpp.exe: warn.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

warn-unused-result.exe: warn-unused-result.c
	$(CC) $(CFLAGS) /Fe$(@) $(?)
warn-unused-result.cpp: warn-unused-result.c
	copy /Y $(?) $(@) >NUL
warn-unused-result-cpp.exe: warn-unused-result.cpp
	$(CXX) $(CXXFLAGS) /Fe$(@) $(?)

